### PR TITLE
registration and login layout done

### PR DESCRIPTION
**Pull request by mehreenpa**

### CODE REVIEW

**Comment by nikhilualberta** [comment]
are you able to run this? does not work for me

**Comment by mehreenpa** [comment]
> are you able to run this? does not work for me

try now

**Comment by naha-s1** [comment]
sign-up-failure-censored
I'm having trouble signing in, so I can't do much to verify this branch

**Comment by mehreenpa** [comment]
> sign-up-failure-censored I'm having trouble signing in, so I can't do much to verify this branch

register an account using a gmail not ualberta

**Comment by naha-s1** [comment]
can I make up a fake account?

**Comment by naha-s1** [comment]
seems not

**Comment by mehreenpa** [comment]
> seems not

what do you mean a fake account it has to be an actual email account (gmail, yahoo ect.)

**Review by krrischahal — APPROVED** [review]

**Review by nikhilualberta — APPROVED** [review]
looks good

**Pull request merged**
